name: SFDC Pull Request
on:  
  push:
  pull_request:
    branches:
      - feature/*
jobs:
  build_check:
    if: ${{ github.ref != 'master'}}
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
