name: SFDC Prod Validation
on:  
  push:
    branches:
      - master
jobs:
  prod_validate:
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir bin && sfdx -v && java -version && ls -la
      - run: node scripts/js/sfbuilds/create-auth-url.js "${{ secrets.PROD_AUTH_URL }}"
      - run: sfdx auth:sfdxurl:store -f "bin/sfdx-url.json" -a SFDC_ORG
      - run: sfdx force:source:deploy --checkonly -m "ApexClass,ApexTrigger,CustomMetadata" -u SFDC_ORG --testlevel=RunSpecifiedTests --runtests "$(node scripts/js/sfbuilds/get-apex-tests.js)"
