name: SFDC Pull Request
on:  
  push:
  pull_request:
    branches:
      - feature/*
jobs:
  build_check:
    if: ${{ github.ref != 'master'}}
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sfdx -v
      - run: java -version
      - run: mkdir bin
      - run: ls -la scripts/js/sfbuilds
      - run: node scripts/js/sfbuilds/create-auth-url.js "${{ secrets.BZBOZ_AUTH_URL }}"
      - run: cat bin/sfdx-url.json
      - run: sfdx auth:sfdxurl:store -f "bin/sfdx-url.json" -a SFDC_ORG
      - run: TEST_CLS=$(node scripts/js/sfbuilds/get-apex-tests.js);
      - run: sfdx force:source:deploy --checkonly -p "force-app/main/default/" -u SFDC_ORG --testlevel=RunSpecifiedTests --runtests "$TEST_CLS"
