name: SFDC Staging Push
on:  
  push:
    branches:
      - develop
jobs:
  staging_push:
    if: ${{ github.ref == 'develop' }}
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sfdx -v && java -version && ls -la
      - run: node scripts/js/sfbuilds/create-auth-url.js "${{ secrets.STAGING_AUTH_URL }}"
      - run: sfdx auth:sfdxurl:store -f "bin/sfdx-url.json" -a SFDC_ORG
      - run: sfdx force:source:deploy -p "force-app/main/default/" -u SFDC_ORG --testlevel=RunSpecifiedTests --runtests "$(node scripts/js/sfbuilds/get-apex-tests.js)"
