name: SFDC Pull Request
on:  
  push:
  pull_request:
    branches:
      - feature/*
jobs:
  build_check:
    if: ${{ github.ref != 'master'}}
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-rc-full
    steps:
      - sfdx -v
