name: SFDC Pull Request
on: 
  pull_request:
    types: [opened, ready_for_review]
  jobs:
    build_check:
      if: ${{ github.ref != 'master'}}
      runs-on: ubuntu-latest
      container:
        image: salesforce/salesforcedx:latest-rc-full
      steps:
        - sfdx -v
